language: rust
matrix:
    fast_finish: true
    include:
        - rust: 1.23.0

sudo: false

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build

script:
  - cargo build --verbose
  - cargo test --verbose

notifications:
    email: false